### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by shan18** [NeurAI-Lab/MIMDepth#1]
Hi MIMDepth Team,

I recently read your MIMDepth paper and wanted to use the architecture presented for my own research related to self-driving tasks.

I see that the code is still missing from the repository so I wanted to ask if you would be publishing your code here? It would be of tremendous help if you could share the code as it would help in accelerating the progress of the project.

Thanks,
Shantanu

**Comment by hemangchawla** [comment]
Hi @shan18 , the code has been made available now. Hope that helps.
